### ISSUE TITLE
Invalid prop `as` supplied

### ISSUE THREAD

**Issue by DSandstorm** [rafrex/react-interactive#11]
I updated to 0.9.0 from 0.8.3 and received this error:
``Warning: Failed prop type: Invalid prop `as` supplied to `Interactive`. ``

Example usage from my code:
```jsx
import { Link } from 'react-router-dom';
import Interactive from 'react-interactive';
import s from '../../styles/app.style';

<Interactive 
    as={Link}
    to={url || `/portal/${this.props.type}/${card.gsx$name}`}
    {...s.link}
    >
    [...]
</Interactive>
```

Downgrading to 0.8.3 resolves this issue. Let me know any other information I can provide to assist you.

**Comment by rafrex** [comment]
Thanks for the heads up, I released version `0.9.1` which fixes this.
