### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by kreba** [rafrex/react-interactive#8]
This library looks very promising! I'd love to use it in conjunction with Typescript.
Are you planning on providing type definitions anytime soon?
I am a JS/TS newbie but I'd be willing to contribute.
Thank you for your consideration.

**Comment by rafrex** [comment]
I don't use Typescript at the moment, so I won't  be adding type definitions. However, if you'd like you can create and publish type definitions for`react-interactive` to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped), which will make this package compatible with TypeScript for all users!

I can answer questions if you run into any confusion about types for the api.

Let me know if you create this and I'll add it to the readme.

**Comment by kreba** [comment]
Thank you for your speedy feedback.

**Comment by DanudeSandstorm** [comment]
Hello @rafrex, I realize this is an old issue, but I've recently added a definition for ``react-interactive`` to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/a70a4e352f7955de9dca6e61ca92a7750c085628/types/react-interactive/index.d.ts). Let me know if I missed anything.
